trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - task: UseNode@1
    inputs:
      version: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'e2e-server'
      publishLocation: 'pipeline'
    displayName: 'Publish build artifact'

- deployment: DeployWebApp
  displayName: 'Deploy to Production'
  environment: 'Production'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: 'e2e-server'
            path: '$(System.DefaultWorkingDirectory)'
          displayName: 'Download Pipeline Artifact'

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'fghjk'
            appType: 'webAppLinux'
            appName: 'Release Pipeline'
            package: '$(System.DefaultWorkingDirectory)/**/*.zip'
            runtimeStack: 'NODE|20-lts'
          displayName: 'Azure Web App Deploy: Release Pipeline'
